#!/usr/bin/env python3
"""上富良野町 ごみ収集カレンダーPDF → コースYAML 生成。

使い方:
    python3 gen_yaml.py <pdf_dir> [out_dir]

<pdf_dir> に令和8年度カレンダーPDF (R08_aka.pdf, R08_ao.pdf, R08_midori.pdf,
R08_higasi.pdf, R08_nisi.pdf) を置いて実行する。PDFの入手元は sources.yaml 参照。

抽出方針 (extract_kamifurano.py):
  - カレンダーグリッドを座標ベースで解析し category->日付 を得る。
  - 週次カテゴリ(年間>=40回: 可燃/生ごみ/プラ)は weekly + overrides(cancelled)、
    月次ローテーション(紙/缶/びん/不燃/ペット/粗大)は monthly_specific。
  - 都市3コースは生ごみ(週2)を分別、農村2コースは生ごみ無し・缶びん統合(缶・ビン)。
"""
import json, datetime, os, sys
from extract_kamifurano import extract_calendar, extract_oversized

FISCAL_START = datetime.date(2026, 4, 1)
FISCAL_END   = datetime.date(2027, 3, 31)
DOW_CODE = ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU']  # Python weekday() 0=Mon

PDF_BASE = "https://www.town.kamifurano.hokkaido.jp/contents/04chomin/0420seikatsu/gomi/calendar"

COURSES = {
    'aka':           dict(name='赤コース',   pdf='R08_aka.pdf',
        areas=['緑町', '旭町', '新町', '東町', '向町', '丘町', '桜町', '南町3丁目', '東中市街地']),
    'ao':            dict(name='青コース',   pdf='R08_ao.pdf',
        areas=['錦町', '中町', '栄町', '泉町', '扇町', '西町', '光町', '北町']),
    'midori':        dict(name='緑コース',   pdf='R08_midori.pdf',
        areas=['富町', '大町', '本町', '宮町', '南町（南町3丁目を除く）']),
    'noson-higashi': dict(name='農村東コース', pdf='R08_higasi.pdf',
        areas=['清富', '日新', '日の出', '旭野', '富原', '東中（東中市街地を除く）']),
    'noson-nishi':   dict(name='農村西コース', pdf='R08_nisi.pdf',
        areas=['草分', '里仁', '江幌', '静修', '江花', '島津']),
}

WEEKLY_THRESHOLD = 40  # 年間これ以上なら週次(weekly)とみなす
CAT_ORDER = ['burnable', 'kitchen', 'plastic', 'pet_bottle', 'paper_cloth',
             'beverage_can', 'glass_bottle', 'non_burnable', 'oversized']


def parse(s):
    y, m, d = map(int, s.split('-')); return datetime.date(y, m, d)


def note_for(d):
    if (d.month == 12 and d.day >= 29) or (d.month == 1 and d.day <= 3):
        return '年末年始'
    return '収集なし'


def build_rule(cat, dates):
    ds = sorted(dates)
    if len(ds) >= WEEKLY_THRESHOLD:
        dows = sorted({parse(d).weekday() for d in ds})
        days = [DOW_CODE[w] for w in dows]
        have = set(ds)
        overrides = []
        d = FISCAL_START
        while d <= FISCAL_END:
            if d.weekday() in dows and d.isoformat() not in have:
                overrides.append({'date': d.isoformat(), 'category': cat,
                                  'cancelled': True, 'note': note_for(d)})
            d += datetime.timedelta(days=1)
        return {'category': cat, 'pattern': 'weekly', 'days': days}, overrides
    return {'category': cat, 'pattern': 'monthly_specific', 'dates': ds}, []


def collect(pdf_path):
    """PDF1本から category->[dates] を得る (粗大ごみ含む)。"""
    from collections import defaultdict
    bycat = defaultdict(list)
    for d, c in extract_calendar(pdf_path):
        bycat[c].append(d)
    out = {c: sorted(v) for c, v in bycat.items()}
    out['oversized'] = extract_oversized(pdf_path)
    return out


def yaml_dump_course(cid, data):
    info = COURSES[cid]
    pdf_url = f"{PDF_BASE}/{info['pdf']}"
    L = []; A = L.append
    A(f"# {info['name']} 2026年度 (令和8年度)")
    A(f"# Auto-generated by tools/pdf-extractor/kamifurano/gen_yaml.py (pdfplumber 機械抽出)")
    A(f"# Source: {pdf_url}")
    A(f"# 曜日規則・年末年始/回収なしの休止まで含め、AI(Claude + pdfplumber)による機械照合済み。")
    A(f"# 人間による目視レビューは未実施。")
    A("metadata:")
    A("  city: kamifurano-town")
    A(f"  course: \"{cid}\"")
    A(f"  course_name_ja: {info['name']}")
    A("  area_names:")
    for a in info['areas']:
        A(f"    - {a}")
    A("  year: 2026")
    A("  fiscal_year_ja: 令和8年度")
    A("  source:")
    A(f"    pdf_url: {pdf_url}")
    A("    extracted_at: 2026-07-10")
    A("    extracted_by: claude-opus-4-8")
    A("    confidence: 0.9")
    A("    verified_by: \"Claude (pdfplumber機械照合、人間による目視レビューは未実施)\"")
    A("rules:")
    all_overrides = []
    for cat in [c for c in CAT_ORDER if data.get(c)]:
        rule, ovs = build_rule(cat, data[cat])
        all_overrides.extend(ovs)
        A(f"  - category: {rule['category']}")
        A(f"    pattern: {rule['pattern']}")
        if rule['pattern'] == 'weekly':
            A("    days:")
            for dcode in rule['days']:
                A(f"      - {dcode}")
        else:
            A("    dates:")
            for d in rule['dates']:
                A(f"      - {d}")
    if all_overrides:
        all_overrides.sort(key=lambda o: o['date'])
        A("overrides:")
        for o in all_overrides:
            A(f"  - date: {o['date']}")
            A(f"    category: {o['category']}")
            A("    cancelled: true")
            A(f"    note: {o['note']}")
    return "\n".join(L) + "\n"


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_yaml.py <pdf_dir> [out_dir]")
    pdf_dir = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join(os.path.dirname(__file__), '..', '..', '..',
                     'cities', 'kamifurano-town', 'data', 'gomi', '2026')
    out_dir = os.path.abspath(out_dir)
    os.makedirs(out_dir, exist_ok=True)
    for cid, info in COURSES.items():
        pdf_path = os.path.join(pdf_dir, info['pdf'])
        data = collect(pdf_path)
        y = yaml_dump_course(cid, data)
        path = os.path.join(out_dir, f"course-{cid}.yaml")
        open(path, 'w').write(y)
        n_over = y.count('cancelled: true')
        print(f"{cid:14} -> {path}  ({sum(len(v) for v in data.values())} dates, {n_over} overrides)")


if __name__ == '__main__':
    main()
